// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXYFIvcZJ-mufvMbD4Thmk6GnV4o6FzKk',
    appId: '1:1002091698201:web:d1c29b4f3612a5fe397288',
    messagingSenderId: '1002091698201',
    projectId: 'dtt-real-estate-79824',
    authDomain: 'dtt-real-estate-79824.firebaseapp.com',
    storageBucket: 'dtt-real-estate-79824.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlHbwEWdL1sLBMLtHnAtpoH7uGPTLbwzE',
    appId: '1:1002091698201:android:5cec2f5b0ce3966e397288',
    messagingSenderId: '1002091698201',
    projectId: 'dtt-real-estate-79824',
    storageBucket: 'dtt-real-estate-79824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDltfub4BU8dwZ8w__j7KCx9nhdKDKz4nM',
    appId: '1:1002091698201:ios:73d8bfccf36b08ab397288',
    messagingSenderId: '1002091698201',
    projectId: 'dtt-real-estate-79824',
    storageBucket: 'dtt-real-estate-79824.firebasestorage.app',
    iosBundleId: 'com.miraskoda.dtt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDltfub4BU8dwZ8w__j7KCx9nhdKDKz4nM',
    appId: '1:1002091698201:ios:73d8bfccf36b08ab397288',
    messagingSenderId: '1002091698201',
    projectId: 'dtt-real-estate-79824',
    storageBucket: 'dtt-real-estate-79824.firebasestorage.app',
    iosBundleId: 'com.miraskoda.dtt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXYFIvcZJ-mufvMbD4Thmk6GnV4o6FzKk',
    appId: '1:1002091698201:web:0df7386f9e7593b2397288',
    messagingSenderId: '1002091698201',
    projectId: 'dtt-real-estate-79824',
    authDomain: 'dtt-real-estate-79824.firebaseapp.com',
    storageBucket: 'dtt-real-estate-79824.firebasestorage.app',
  );
}
